
package web.service.client.importer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceDisponabilite", targetNamespace = "http://service.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceDisponabilite {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @param arg8
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "afficherOffres2", targetNamespace = "http://service.example.com/", className = "web.service.client.importer.AfficherOffres2")
    @ResponseWrapper(localName = "afficherOffres2Response", targetNamespace = "http://service.example.com/", className = "web.service.client.importer.AfficherOffres2Response")
    @Action(input = "http://service.example.com/WebServiceDisponabilite/afficherOffres2Request", output = "http://service.example.com/WebServiceDisponabilite/afficherOffres2Response", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.example.com/WebServiceDisponabilite/afficherOffres2/Fault/Exception")
    })
    public String afficherOffres2(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Double arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        Double arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns web.service.client.importer.Offre
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOffre", targetNamespace = "http://service.example.com/", className = "web.service.client.importer.GetOffre")
    @ResponseWrapper(localName = "getOffreResponse", targetNamespace = "http://service.example.com/", className = "web.service.client.importer.GetOffreResponse")
    @Action(input = "http://service.example.com/WebServiceDisponabilite/getOffreRequest", output = "http://service.example.com/WebServiceDisponabilite/getOffreResponse")
    public Offre getOffre();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setOffre", targetNamespace = "http://service.example.com/", className = "web.service.client.importer.SetOffre")
    @ResponseWrapper(localName = "setOffreResponse", targetNamespace = "http://service.example.com/", className = "web.service.client.importer.SetOffreResponse")
    @Action(input = "http://service.example.com/WebServiceDisponabilite/setOffreRequest", output = "http://service.example.com/WebServiceDisponabilite/setOffreResponse")
    public void setOffre(
        @WebParam(name = "arg0", targetNamespace = "")
        Offre arg0);

}
