
package web.service.client.reservation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "webSeviceReservation", targetNamespace = "http://service.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebSeviceReservation {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimerReservation", targetNamespace = "http://service.example.com/", className = "web.service.client.reservation.SupprimerReservation")
    @ResponseWrapper(localName = "supprimerReservationResponse", targetNamespace = "http://service.example.com/", className = "web.service.client.reservation.SupprimerReservationResponse")
    @Action(input = "http://service.example.com/webSeviceReservation/supprimerReservationRequest", output = "http://service.example.com/webSeviceReservation/supprimerReservationResponse")
    public String supprimerReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        Reservation arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterReservation", targetNamespace = "http://service.example.com/", className = "web.service.client.reservation.AjouterReservation")
    @ResponseWrapper(localName = "ajouterReservationResponse", targetNamespace = "http://service.example.com/", className = "web.service.client.reservation.AjouterReservationResponse")
    @Action(input = "http://service.example.com/webSeviceReservation/ajouterReservationRequest", output = "http://service.example.com/webSeviceReservation/ajouterReservationResponse")
    public String ajouterReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Reservation arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Client arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5);

}
